<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErGMILr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErGMILr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErGMILr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErGMILr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErGMILr\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErGMILr',
    'container.build_id' => '800ea32f',
    'container.build_time' => 1662548185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErGMILr');
