<?php

namespace ContainerZfwJ2hi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\TransactionService' shared autowired service.
     *
     * @return \App\Service\TransactionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TransactionService.php';

        return $container->privates['App\\Service\\TransactionService'] = new \App\Service\TransactionService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
